# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 59c9eab3cd876df77c0ca94f7453d3d70aec0bcd2ba52dcad8a331ee7082d3afca57c5cca3cc6008bb9e7e12ab9c26398fa5ef485dadb1102cd034fe6ae05171

test:
  secret_key_base: de71a60a8e90b5264a06b550e12687aecbf850c1c16dc365ee41370693f9b028b908880b43c3781e25e35de848d3fd782896d8d94cb0010d36431e087f9de200

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
